# Site settings
title: Sumit Gupta
email: 
description: >
baseurl: ""
url: "http://guptaasumit.com" # the base hostname & protocol for your site
github_username:  timusg

# Build settings
markdown: kramdown
