# Site settings
title: Sumit Gupta
email: 
description: >
baseurl: ""
url: "http://guptasumit.com" # the base hostname & protocol for your site
github_username:  timusg

# Build settings
markdown: kramdown
google_analytics: UA-132915390-1
